spring:
  datasource:
    url: jdbc:mysql://${db.host:localhost}/fiapark-api?createDatabaseIfNotExist=true
    username: ${db.user}
    password: ${db.password}
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.user}
    password: ${rabbitmq.password}
    ssl:
      enabled: false
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1s
          multiplier: 2
        default-requeue-rejected: true
springdoc:
  swagger-ui:
    path: /docs.html