spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email.user}
    password: ${email.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  freemarker:
    settings:
      locale: pt_BR
  rabbitmq:
    ssl:
      enabled: false
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.user}
    password: ${rabbitmq.password}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1s
          multiplier: 2
        default-requeue-rejected: false
server:
  port: 8082